### ISSUE TITLE
default_bot_config.json not written on fresh install since nedry==2.2.0

### ISSUE THREAD

**Issue by rkantos** [eriknyquist/nedry#2]
Really as simple as it is described. When installing Nedry from pypi, I can only get the default_bot_config.json to appear when using the first version available, 2.1.0. On subsequent versions `Created default config file 'default_bot_config.json', please add required parameters` is output but there is no file to be found. Debian/Ubuntu as platform with deadsnakes python3.9 and default python3-pip package.

**Comment by eriknyquist** [comment]
Thank you, I just released 2.4.1 to fix this

**Comment by rkantos** [comment]
Working since nedry==2.4.1
